custom:
  memory_condition: '2'
recording:
  channels: 1
  device_index: 3
  samplerate: 48000
settings:
  data_path: ./data
  device: cpu
  icebreaker_question_count: 10
  k: 3
  lstm_model_path: ./models/cnn_lstm.keras
  user: hello
  user_path: ./data/hello
